name: Deploy React App to Cafe24 via FTP

on:
  push:
    branches:
      - main   # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Node.js 세팅
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Vite 권장 버전

      # 3️⃣ 의존성 설치
      - name: Install dependencies
        run: npm install
        working-directory: ./my-portfolio

      # 4️⃣ 빌드
      - name: Build project
        run: npm run build
        working-directory: ./my-portfolio

      # 5️⃣ React Router SPA 처리
      - name: Handle React Router SPA
        working-directory: ./my-portfolio
        run: cp dist/index.html dist/404.html

      # 6️⃣ FTP 배포
      - name: Deploy to Cafe24 via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.CAFE24_FTP_SERVER }}      # 예: myport.cafe24.com
          username: ${{ secrets.CAFE24_FTP_USERNAME }}  # FTP 계정 ID
          password: ${{ secrets.CAFE24_FTP_PASSWORD }}  # FTP 비밀번호
          local-dir: ./my-portfolio/dist/               # 빌드 결과물
          server-dir: /www/                             # 서버 루트
          dangerous-clean-slate: false                  # 기존 파일 삭제 안 함
          git-ftp-args: --ftp-create-dirs              # 폴더가 없으면 자동 생성
